### ISSUE TITLE
Endless Loading Screen on intel Mac

### ISSUE THREAD

**Issue by kevinpsmit** [krud-dev/boost#379] opened 2023-04-25 20:28 UTC
## Prerequisites

- [ ] Using npm
- [ ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Expected the main screen to come up after some time

## Current Behavior

The application stays on the loading screen indefinitely.

## Steps to Reproduce

Open application

## Context

This only seemed to affect the intel release (on both an intel mac and arm mac), but not the arm64 build. I'm happy to provide logs if you tell me where to look.

## Your Environment

Mac OS Ventura 13.3.1 Intel & ARM

- Node version : n/a
- electron-react-boilerplate version or branch : n/a
- Operating System and version : Mac OS Ventura 13.3.1 
- Link to your project :

**Comment by Idane** [comment] 2023-04-25 20:35
Logs will be in ~/Library/Logs/@krud-dev/boost

**Comment by kevinpsmit** [comment] 2023-04-25 20:44
I tried running the intel build first on an intel mac, but then again on my arm mac. Attached are the logs. Looks like an issue with sqlite.
[main.log](https://github.com/krud-dev/boost/files/11326702/main.log)

**Comment by Idane** [comment] 2023-04-25 23:09
Okay, so intel build on ARM mac won't work and that's working as intended, looking into the intel on intel situation.

**Comment by Idane** [comment] 2023-04-25 23:42
I'm going to produce a special build before I merge #380 as I personally don't have an Intel mac to test this on

**Comment by Idane** [comment] 2023-04-26 01:04
@kevinpsmit @avivm 
Seems to also work on M1, could you please take a look and see if this build works for you?
https://slack-files.com/T01C151H151-F054Y47FLHG-58e12598a7

**Comment by kevinpsmit** [comment] 2023-04-26 23:14
@Idane Sorry for the delayed response. That build does the trick!

**Comment by Idane** [comment] 2023-04-26 23:32
Glad to hear! Will do a release soon.

**Closed** 2023-04-26 23:32 UTC
Labels: bug
